#include <algorithm>
#include <cmath>
#include <fstream>
#include <iostream>
#include <numeric>
#include <string>
#include <vector>
#include <nlohmann/json.hpp>
using json=nlohmann::json;
static json read_json(const std::string& p){std::ifstream f(p);json x;f>>x;return x;}
static double yf(int a,int b){return std::max(b-a,0)/365.0;}
struct Result{double pv{},put{},coupon{},ki{},ko{};std::vector<double> fixings,memory;};
static Result price(const json& common,const std::vector<double>& paths,std::size_t P,std::size_t O,const std::vector<int>& dates){
 const auto& d=common.at("dealData"); const auto& m=common.at("marketData"); const auto& u=d.at("instrument").at("underlyings");
 const double r=m.at("discCurves").at(0).at("curve").at(0).value("rate",0.0), df=std::exp(-r*yf(m.at("evaluationDate"),d.value("expiryDate",d.value("maturityDate",m.at("evaluationDate")))));
 double refs[2]={u.at(0).value("spot",100.0),u.at(1).value("spot",100.0)}; const auto& rg=d.value("RGACCLKO",json::object());
 const double strike=d.value("knockInStar",json::object()).value("strikeKI2",d.value("strike",0.78)); const double kib=d.value("knockInStar",json::object()).value("KIBarrier",0.70); const double gkb=rg.value("gblBarPrice",1.10); const int expiry=d.value("expiryDate",d.value("maturityDate",m.at("evaluationDate"))); const std::size_t EO=static_cast<std::size_t>(std::upper_bound(dates.begin(),dates.end(),expiry)-dates.begin());
 std::vector<char> ki(P,0),ko(P,0); std::vector<std::size_t> ko_step(P,O); std::vector<double> terminal_worst(P,1.0);
 for(std::size_t p=0;p<P;++p){for(std::size_t o=0;o<EO;++o){double a=paths[(p*O+o)*2]/refs[0],b=paths[(p*O+o)*2+1]/refs[1],w=std::min(a,b); if(w<=kib)ki[p]=1; if(!ko[p]&&a>=gkb&&b>=gkb){ko[p]=1;ko_step[p]=o;}} terminal_worst[p]=std::min(paths[(p*O+EO-1)*2]/refs[0],paths[(p*O+EO-1)*2+1]/refs[1]);}
 double put=0; for(std::size_t p=0;p<P;++p) if(ki[p]&&!ko[p]) put+=std::max(strike-terminal_worst[p],0.0); put=put/P*df;
 const auto ends=rg.value("endDate",std::vector<int>{}), pays=rg.value("paymentDate",std::vector<int>{}); const auto rates=rg.value("accruRate",std::vector<double>{}); const auto n1=rg.value("N1",std::vector<int>{}), n2=rg.value("N2",std::vector<int>{}); const auto lows=rg.value("lowRange",std::vector<double>{}), ups=rg.value("upRange",std::vector<double>{});
 const double notional=d.value("notional",1.0); std::vector<double> cash(P,0),memory(P,0); int previous=m.at("evaluationDate"); Result out; out.put=put; out.ki=std::accumulate(ki.begin(),ki.end(),0.0)/P; out.ko=std::accumulate(ko.begin(),ko.end(),0.0)/P;
 for(std::size_t i=0;i<ends.size()&&i<pays.size()&&i<rates.size()&&i<n1.size()&&i<n2.size();++i){auto it1=std::upper_bound(dates.begin(),dates.end(),ends[i]);auto it0=std::upper_bound(dates.begin(),dates.end(),previous); if(ends[i]<dates.front()){previous=ends[i];continue;} std::size_t e=it1==dates.begin()?0:static_cast<std::size_t>(it1-dates.begin()-1),s=static_cast<std::size_t>(it0-dates.begin()); if(e<s||rates[i]==0){previous=ends[i];continue;} double low=i<lows.size()?lows[i]:0,up=i<ups.size()?ups[i]:1e9; std::vector<double> obs(P,0); for(std::size_t p=0;p<P;++p){for(std::size_t o=s;o<=e&&o<O;++o){double a=paths[(p*O+o)*2]/refs[0],b=paths[(p*O+o)*2+1]/refs[1],w=std::min(a,b);if(w>=low&&w<=up)obs[p]++;} double future=std::max(obs[p]-n1[i],0.0), total=std::max(n2[i],1); double frac=std::min((future+memory[p])/total,1.0); if(ko_step[p]>e)cash[p]+=notional*rates[i]*frac*std::exp(-r*yf(m.at("evaluationDate"),pays[i])); memory[p]=(ko_step[p]>e&&future<total)?std::max(total-future,0.0):0;} out.fixings.push_back(std::accumulate(obs.begin(),obs.end(),0.0)/P);out.memory.push_back(std::accumulate(memory.begin(),memory.end(),0.0)/P);previous=ends[i];}
 double raw=std::accumulate(cash.begin(),cash.end(),0.0)/P; out.coupon=raw/std::max(notional,1.0)*d.value("legacyCouponQuoteScale",10.0); out.pv=df-out.put+out.coupon; return out;
}
int main(int argc,char**argv){if(argc<3){std::cerr<<"usage: daily_termsheet termsheet.json daily_paths.bin\n";return 2;}auto root=read_json(argv[1]);auto meta=read_json(std::string(argv[2])+".meta.json");std::size_t P=meta.at("paths"),O=meta.at("observations");std::ifstream f(argv[2],std::ios::binary);std::vector<double> paths(P*O*2);f.read(reinterpret_cast<char*>(paths.data()),static_cast<std::streamsize>(paths.size()*sizeof(double)));auto jobs=root.at("Chunk").at("Jobs");std::vector<int> dates=meta.at("dates").get<std::vector<int>>();auto canonical=[&](const std::vector<double>& x){std::vector<Result> q;for(const auto& j:jobs)q.push_back(price(j.at("commonData"),x,P,O,dates));return q[0].pv-q[0].coupon+(q.size()>2?q[2].coupon:q[0].coupon);};std::vector<Result> rs;for(const auto& j:jobs)rs.push_back(price(j.at("commonData"),paths,P,O,dates));double coupon=rs.size()>2?rs[2].coupon:rs[0].coupon;double pv=rs[0].pv-rs[0].coupon+coupon;std::vector<double> spots={paths[0],paths[1]},deltas,gammas;for(int u=0;u<2;++u){auto up=paths,down=paths;for(std::size_t p=0;p<P;++p)for(std::size_t o=0;o<O;++o){up[(p*O+o)*2+u]*=1.01;down[(p*O+o)*2+u]*=.99;}double pu=canonical(up),pd=canonical(down);deltas.push_back((pu-pd)/.02);gammas.push_back((pu-2*pv+pd)/.0001);}json out={{"engine","cpp_daily_termsheet"},{"daily_observations",O},{"job_pvs",json::array()},{"job_put_prices",json::array()},{"job_coupon_pvs",json::array()},{"pv",pv},{"put_price",rs[0].put},{"coupon_pv",coupon},{"relative_delta",deltas},{"relative_gamma",gammas},{"ki_probability",rs[0].ki},{"ko_probability",rs[0].ko},{"coupon_fixings",rs.size()>2?rs[2].fixings:rs[0].fixings},{"memory_carry",rs.size()>2?rs[2].memory:rs[0].memory}};for(auto&r:rs){out["job_pvs"].push_back(r.pv);out["job_put_prices"].push_back(r.put);out["job_coupon_pvs"].push_back(r.coupon);}std::cout<<out.dump(2)<<"\n";}
